"""empty message

Revision ID: e84163bbb54a
Revises: ed588faf6a59
Create Date: 2026-02-27 19:43:48.893917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e84163bbb54a'
down_revision: Union[str, Sequence[str], None] = 'ed588faf6a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('hint', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('correct_answer', sa.Text(), nullable=True))
    op.add_column('themes', sa.Column('theory', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('themes', 'theory')
    op.drop_column('tasks', 'correct_answer')
    op.drop_column('tasks', 'hint')
    # ### end Alembic commands ###
